apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-web
  annotations:
    # Send people from http to https automatically.
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - demo.example.com
      secretName: demo-web-tls

  rules:
    - host: demo.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-web
                port:
                  name: http
